language: php
php:
  - 5.6
  - 7.0
before_install:
  - mysql -e "create database IF NOT EXISTS rssnext;" -uroot
  - mysql -uroot rssnext < rssnext.sql
before_script:
  - sed -i '/phpdoc/d' composer.json
  - printf "<?php\ndefine('DB_USERNAME', 'root');\ndefine('DB_PASSWORD','');\n" > local_settings.php
  - composer install
script:
  - phpunit --configuration test/phpunit.xml test
  - ./vendor/bin/phpcs --ignore=*/vendor/*,*/test/*,*/bin/*,*bootstrap.css,*settings.php --standard=PSR2 .
after_script:
  - vendor/bin/test-reporter