language: php
php:
  - 5.6
  - 7.0
addons:
  hosts:
    - local.rssnext.net
before_install:
  - mysql -e "create database IF NOT EXISTS rssnext;" -uroot
  - mysql -uroot rssnext < rssnext.sql
before_script:
  - sed -i '/phpdoc/d' composer.json
  - printf "<?php\ndefine('DB_USERNAME', 'root');\ndefine('DB_PASSWORD','');\n" > local_settings.php
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "php -S localhost:8001 -t public_html/ > /dev/null 2>&1 &"
  - sleep 3
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.15.0.jar
  - java -jar selenium-server-standalone-2.15.0.jar > /dev/null 2>&1 &
  - sleep 15  # to wait for Selenium to be up and running
  - composer install
script:
  - phpunit -v --configuration test/phpunit.xml test
  - ./vendor/bin/phpcs --ignore=*/vendor/*,*/test/*,*/bin/*,*bootstrap.css,*settings.php --standard=PSR2 .
after_script:
  - vendor/bin/test-reporter